<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>{{pdf_row_separator}}
<?php $trans_id = $this->getInfo()->getLastTransId(); ?>
<?php if (!empty($trans_id)): ?>
    <?php $specific = $this->getSpecificInformation(); ?>
    <?php if (count($specific) > 0): ?>
        <?php foreach($specific as $key => $value): ?>
            <?php unset($specific['Authenticated Status']); ?>
            <?php unset($specific['Transaction Ref']); ?>
            <?php unset($specific['PayEx Transaction Status']); ?>
            <?php echo Mage::helper('payex')->__($key) . ': ' . $value; ?>
            {{pdf_row_separator}}
        <?php endforeach; ?>
    <?php endif; ?>
<?php else: ?>
    <?php echo Mage::helper('paygate')->__('Payment has not been processed yet.'); ?>
<?php endif; ?>
