<?php
/** @var $this PayEx_Payments_Block_Form_Invoice */

// Get fee
$fee = $this->getPayexPaymentFee();
?>
<script type="text/javascript">
    var pxInvoiceForm = Class.create();
    pxInvoiceForm.prototype = {
        switchMethod: function (method) {
            // Get current method
            if (method == 'private') {
                var method_to_disable = 'corporate';
            } else {
                var method_to_disable = 'private';
            }

            // Disable sections
            var form = $('pxinvoice_' + method_to_disable);
            form.hide();
            var elements = form.getElementsByTagName('input');
            for (var i = 0; i < elements.length; i++) {
                $(elements[i]).removeClassName('required-entry');
            }

            // Enable sections
            var form = $('pxinvoice_' + method);
            form.show();
            var elements = form.getElementsByTagName('input');
            for (var i = 0; i < elements.length; i++) {
                $(elements[i]).addClassName('required-entry');
            }
        }
    }

    Varien.pxInvoiceForm_switchMethod = function (method) {
        return pxInvoiceForm.prototype.switchMethod(method);
    }
</script>
<fieldset class="form-list">
    <?php $_code = $this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div style="float:left">
                <img src="<?php echo Mage::getDesign()->getSkinUrl('images/payex/payex-invoice.png'); ?>"/>
            </div>
            <div style="float:left">
                <!-- Start PayEx Invoice block -->
                <form action="<?php echo $this->getFormAction(); ?>" method="post">
                    <p><?php echo Mage::helper('payex')->__('Select Invoice Type:'); ?></p>
                    <ul class="form-list">
                        <li class="control">
                            <input type="radio" name="pxinvoice_method" id="pxinvoice_method:private" value="private"
                                   class="radio" onclick="Varien.pxInvoiceForm_switchMethod('private');" checked/>
                            <label
                                for="pxinvoice_method:private"><?php echo Mage::helper('payex')->__('Private'); ?></label>
                            <br/>

                            <div id="pxinvoice_private" class="input-box">
                                <label
                                    for="socialSecurityNumber"><?php echo Mage::helper('payex')->__('Social Security Number'); ?>
                                    <span class="required">*</span></label><br/>
                                <input name="socialSecurityNumber" id="socialSecurityNumber"
                                       title="Social Security Number" value="Social Security Number"
                                       class="required-entry input-text" type="text"/><br/>
                                <label for="firstName"><?php echo Mage::helper('payex')->__('First name'); ?>
                                    <span class="required">*</span></label><br/>
                                <input name="firstName" id="firstName" title="First name" value="First name"
                                       class="required-entry input-text" type="text"/><br/>
                                <label for="lastName"><?php echo Mage::helper('payex')->__('Last name'); ?><span
                                        class="required">*</span></label><br/>
                                <input name="lastName" id="lastName" title="Last name" value="Last name"
                                       class="required-entry input-text" type="text"/><br/>
                            </div>
                        </li>
                        <li class="control">
                            <input type="radio" name="pxinvoice_method" id="pxinvoice_method:corporate"
                                   value="corporate" class="radio"
                                   onclick="Varien.pxInvoiceForm_switchMethod('corporate');"/>
                            <label
                                for="pxinvoice_method:corporate"><?php echo Mage::helper('payex')->__('Corporate'); ?></label>
                            <br/>

                            <div id="pxinvoice_corporate" class="input-box" style="display: none;">
                                <label
                                    for="organizationNumber"><?php echo Mage::helper('payex')->__('Organization Number'); ?>
                                    <span class="required">*</span></label><br/>
                                <input name="organizationNumber" id="organizationNumber"
                                       title="Social Security Number" value="Organization Number"
                                       class="input-text" type="text"/><br/>
                            </div>
                        </li>
                    </ul>
                </form>
                <?php if ($fee > 0): ?>
                <div><strong><?php echo Mage::helper('payex')->__('Payment fee'); ?>:</strong>
                    <?php echo Mage::helper('core')->currency($fee); ?>
                </div>
                <?php endif; ?>
                <!-- End PayEx Invoice block -->
            </div>
            <div style="float:right"></div>
        </li>
    </ul>
</fieldset>
