<style type="text/css">
#payment_form_payex2 ul.cards-logo li {
    float: left;
}
</style>
<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div style="float:left">
                <img src="<?php echo Mage::getDesign()->getSkinUrl('images/payex2/payex-small.gif'); ?>" alt="PayEx" /><br />
            </div>
            <div style="float:left">
                <?php echo Mage::helper('payex2')->__('You will be redirected to <a target="_blank" href="http://www.payex.com">PayEx</a> website when you place an order.'); ?>
            </div>
            <div class="clearfix">&nbsp;</div>
            <ul class="cards-logo">
                <li><img src="<?php echo Mage::getDesign()->getSkinUrl('images/payex2/visa_64.png'); ?>" /></li>
                <li><img src="<?php echo Mage::getDesign()->getSkinUrl('images/payex2/mastercard_64.png'); ?>" /></li>
                <li><img src="<?php echo Mage::getDesign()->getSkinUrl('images/payex2/diners_club_64.png'); ?>" /></li>
                <li><img src="<?php echo Mage::getDesign()->getSkinUrl('images/payex2/jcb_64.png'); ?>" /></li>
                <li><img src="<?php echo Mage::getDesign()->getSkinUrl('images/payex2/american_express_64.png'); ?>" /></li>
            </ul>
        </li>
    </ul>
</fieldset>