<?php
    $specific = $this->getSpecificInformation();
?>

<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?>
    {{pdf_row_separator}}
<?php if (count($specific) > 0): ?>
    <?php foreach($specific as $key => $value): ?>
        <?php echo Mage::helper('payex2')->__($key) . ': ' . $this->htmlEscape($value); ?>
        {{pdf_row_separator}}
    <?php endforeach; ?>
<?php endif; ?>
    {{pdf_row_separator}}