<?php
/**
 * @var $this AAIT_Factoring_Block_Checkout_Fee
 */
?>
<!-- Start Factoring Payment Fee -->
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php echo $this->helper('factoring')->__('Payment fee'); ?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->getPaymentFee()) ?>
    </td>
</tr>
<!-- End Factoring Payment Fee -->