<div id="payex-settings-hint">
    <p><?php echo Mage::helper('payex2')->__('Thank you for using the official PayEx module for Magento!'); ?></p>
    <br />
    <p><?php echo Mage::helper('payex2')->__('You use follow extensions:'); ?></p>
    <ul class="modules">
        <?php foreach ($modules as $module => $version) : ?>
            <li>
                <?php echo $module . ' ' . $version['current_version']; ?>
            <?php if (version_compare($version['current_version'], $version['last_version'], '<')): ?>
                <span class="last-version"> (<?php echo Mage::helper('payex2')->__('Available: %s', $version['last_version']); ?>)</span>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
