<?php
/** @var $this PayEx_Payments_Block_Form_Financing */

// Get saved SSN from SSN extension
$socal_security_number = $this->getPayexSSN();

// Get fee
$fee = $this->getPayexPaymentFee();
?>

<fieldset class="form-list">
    <?php $_code = $this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div style="float:right">
                <img src="<?php echo Mage::getDesign()->getSkinUrl('images/payex/financing-logo.gif'); ?>"/>
            </div>
            <div style="float:left">
                <!-- Start PayEx Financing block -->
                <form action="<?php echo $this->getFormAction(); ?>" method="post">
                    <?php if (empty($socal_security_number)): ?>
                        <label
                            for="social-security-number"><?php echo Mage::helper('payex')->__('Social Security Number'); ?>
                            <span class="required">*</span></label><br/>
                        <input name="social-security-number" id="social-security-number"
                               title="<?php echo Mage::helper('payex')->__('Social Security Number'); ?>" value="<?php echo Mage::helper('payex')->__('Social Security Number'); ?>"
                               class="required-entry input-text" type="text"/><br/>
                    <?php else: ?>
                        <label
                            for="social-security-number"><?php echo Mage::helper('payex')->__('Social Security Number'); ?>
                            <span class="required">*</span></label><br/>
                        <input name="social-security-number" id="social-security-number"
                               title="<?php echo Mage::helper('payex')->__('Social Security Number'); ?>" value="<?php echo $socal_security_number; ?>"
                               class="required-entry input-text" type="text" readonly/><br/>
                    <?php endif; ?>
                </form>
                <?php if ($fee->getPaymentFeePrice() > 0): ?>
                <div>
                    <?php if ($this->helper('tax')->displayBothPrices()): ?>
                        <strong><?php echo Mage::helper('payex')->__('Payment fee'); ?>:</strong>
                        <br />
                        <?php echo $this->helper('checkout')->formatPrice($fee->getPaymentFeePrice()); ?>
                        <?php echo $this->helper('checkout')->__('(Excl. Tax)'); ?>
                        <br />
                        <?php echo $this->helper('checkout')->formatPrice($fee->getPaymentFeePrice() + $fee->getPaymentFeeTax()); ?>
                        <?php echo $this->helper('checkout')->__('(Incl. Tax)'); ?>
                    <?php elseif ($this->helper('tax')->displayPriceIncludingTax()): ?>
                        <strong><?php echo Mage::helper('payex')->__('Payment fee'); ?>:</strong>
                        <?php echo $this->helper('checkout')->formatPrice($fee->getPaymentFeePrice() + $fee->getPaymentFeeTax()); ?>
                    <?php else: ?>
                        <strong><?php echo Mage::helper('payex')->__('Payment fee'); ?>:</strong>
                        <?php echo $this->helper('checkout')->formatPrice($fee->getPaymentFeePrice()); ?>
                    <?php endif; ?>
                </div>
                <?php endif; ?>
                <!-- End PayEx Financing block -->
            </div>
            <div style="float:right"></div>
        </li>
    </ul>
</fieldset>
