<?php
/** @var $this PayEx_Payments_Block_Form_Autopay */

// Get Agreement Data
$agreement_id = Mage::helper('payex/agreement')->getCustomerAgreement();
$agreement_url = Mage::getSingleton('payex/payment_autopay')->getConfigData('agreementurl');
$agreement_link = Mage::helper('payex')->__('<a target="_blank" href="%s">agreement</a>', $agreement_url);
$agreement_status = Mage::helper('payex/agreement')->getPxAgreementStatus($agreement_id);
?>
<style type="text/css">
    #payment_form_payex_autopay ul.cards-logo li {
        float: left;
    }
</style>
<fieldset class="form-list">
    <?php $_code = $this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div style="float:left">
                <img src="<?php echo Mage::getDesign()->getSkinUrl('images/payex/payex-small.gif'); ?>" />
            </div>
            <div style="float:left">
                <!-- Start PayEx Autopay block -->
                <form action="<?php echo $this->getFormAction(); ?>" id="payexAutopayForm" method="post">
                    <div class="input-box">
                        <?php if ($agreement_status === PayEx_Payments_Model_Payment_Autopay::AGREEMENT_NOTEXISTS): ?>
                            <?php echo Mage::helper('payex')->__('You will be redirected to <a target="_blank" href="http://www.payex.com">PayEx</a> website when you place an order.'); ?>
                            <?php echo Mage::helper('payex')->__('Sign a %s to streamline further purchases with PayEx.', $agreement_link); ?>
                            <br/>
                            <label
                                for="payex_agreement"><?php echo Mage::helper('payex')->__('I accept the agreement'); ?>
                                <span class="required">*</span>
                                <input name="payex_agreement" id="payex_agreement" title="<?php echo Mage::helper('payex')->__('I accept the agreement'); ?>" value="1"
                                       class="required-entry checkbox" type="checkbox"/>
                            </label>
                        <?php else: ?>
                            <?php echo Mage::helper('payex')->__('You already have an <a target="_blank" href="%s">agreement</a>.', $agreement_url); ?>
                            <br/>
                            <?php echo Mage::helper('payex')->__('Payment will be automatically charged on your card.'); ?>
                            <br/>
                            <?php
                            $cancel_agreement_url = Mage::getUrl('payex/autopay/cancel_agreement', array('_secure' => true));
                            $cancel_agreement_url = "javascript:if(window.confirm('" . Mage::helper('payex')->__('Cancel agreement?') . "')) { self.location.href = '" . $cancel_agreement_url . "' };";
                            echo '<a href="' . $cancel_agreement_url . '">' . Mage::helper('payex')->__('Cancel agreement') . '</a>';
                            ?>
                        <?php endif ?>
                    </div>
                </form>
                <!-- End PayEx Autopay block -->
            </div>
            <div class="clearfix">&nbsp;</div>
            <ul class="cards-logo">
                <li><img src="<?php echo Mage::getDesign()->getSkinUrl('images/payex/visa_64.png'); ?>" /></li>
                <li><img src="<?php echo Mage::getDesign()->getSkinUrl('images/payex/mastercard_64.png'); ?>" /></li>
                <li><img src="<?php echo Mage::getDesign()->getSkinUrl('images/payex/diners_club_64.png'); ?>" /></li>
                <li><img src="<?php echo Mage::getDesign()->getSkinUrl('images/payex/jcb_64.png'); ?>" /></li>
                <li><img src="<?php echo Mage::getDesign()->getSkinUrl('images/payex/american_express_64.png'); ?>" /></li>
            </ul>
        </li>
    </ul>
</fieldset>