<div id="payex-settings-hint">
    <p>
        <?php echo Mage::helper('payex')->__('Thank you for using the official PayEx Payments module for Magento!'); ?>
        <br/>
        <?php echo Mage::helper('payex')->__('Check out the code on %s', '<a href="https://github.com/PayEx/Magento-modules" target="_blank">Github</a>'); ?>
    </p>
    <p>
        <?php echo Mage::helper('payex')->__('Version: %s', $current_version); ?>
        <?php if (version_compare($current_version, $last_version, '<')): ?>
        <br />
        <span class="last-version"><?php echo Mage::helper('payex')->__('Update Available: %s', $last_version); ?></span>
        <?php endif; ?>
    </p>
</div>
