<fieldset class="form-list">
    <?php $_code = $this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div style="float:right">
                <img src="<?php echo Mage::getDesign()->getSkinUrl('images/partpayment/logo.gif'); ?>"/>
            </div>
            <div style="float:left">
                <!-- Start PayEx PartPayment block -->
                <form action="<?php echo $this->getFormAction(); ?>" method="post">
                    <label
                        for="social-security-number"><?php echo Mage::helper('partpayment')->__('Social Security Number'); ?>
                        <span class="required">*</span></label><br/>
                    <input name="social-security-number" id="social-security-number"
                           title="<?php echo Mage::helper('partpayment')->__('Social Security Number'); ?>" value="<?php echo Mage::helper('partpayment')->__('Social Security Number'); ?>"
                           class="required-entry input-text" type="text"/><br/>
                </form>
                <div><strong><?php echo Mage::helper('partpayment')->__('Payment fee'); ?>:</strong>
                    <?php echo Mage::helper('core')->currency(Mage::getSingleton('partpayment/fee')->getPaymentFee()); ?>
                </div>
                <!-- End PayEx PartPayment block -->
            </div>
            <div style="float:right"></div>
        </li>
    </ul>
</fieldset>
