<?php
/**
 * @see AAIT_Factoring_Block_Form
 */

// Get saved SSN from SSN extension
$socal_security_number = $this->getPayexSSN();
?>

<fieldset class="form-list">
    <?php $_code = $this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div style="float:right">
                <img src="<?php echo Mage::getDesign()->getSkinUrl('images/factoring/logo.gif'); ?>"/>
            </div>
            <div style="float:left">
                <!-- Start PayEx Factoring block -->
                <form action="<?php echo $this->getFormAction(); ?>" method="post">
                    <?php if (Mage::getSingleton('factoring/payment')->getConfigData('mode') === 'SELECT'): ?>
                        <label for="factoring-menu">
                            <?php echo Mage::helper('factoring')->__('Please select payment method'); ?><span class="required">*</span>
                        </label>
                        <br/>
                        <select name="factoring-menu" id="factoring-menu" class="required-entry">
                            <option selected value="FINANCING"><?php echo Mage::helper('factoring')->__('Financing Invoice'); ?></option>
                            <!-- <option value="FACTORING"><?php echo Mage::helper('factoring')->__('Invoice 2.0 (Factoring)'); ?></option> -->
                            <option value="CREDITACCOUNT"><?php echo Mage::helper('factoring')->__('Part Payment'); ?></option>
                        </select>
                        <br/>
                    <?php endif; ?>
                    <?php if (empty($socal_security_number)): ?>
                        <label
                            for="social-security-number"><?php echo Mage::helper('factoring')->__('Social Security Number'); ?>
                            <span class="required">*</span></label><br/>
                        <input name="social-security-number" id="social-security-number"
                               title="<?php echo Mage::helper('factoring')->__('Social Security Number'); ?>" value="<?php echo Mage::helper('factoring')->__('Social Security Number'); ?>"
                               class="required-entry input-text" type="text"/><br/>
                    <?php else: ?>
                        <label
                            for="social-security-number"><?php echo Mage::helper('factoring')->__('Social Security Number'); ?>
                            <span class="required">*</span></label><br/>
                        <input name="social-security-number" id="social-security-number"
                               title="<?php echo Mage::helper('factoring')->__('Social Security Number'); ?>" value="<?php echo $socal_security_number; ?>"
                               class="required-entry input-text" type="text" readonly/><br/>
                    <?php endif; ?>
                </form>
                <div><strong><?php echo Mage::helper('factoring')->__('Payment fee'); ?>:</strong>
                    <?php echo Mage::helper('core')->currency(Mage::getSingleton('factoring/fee')->getPaymentFee()); ?>
                </div>
                <!-- End PayEx Factoring block -->
            </div>
            <div style="float:right"></div>
        </li>
    </ul>
</fieldset>
