<?php
/** @var $this PayEx_Payments_Block_Form_PartPayment */

// Get saved SSN from SSN extension
$socal_security_number = $this->getPayexSSN();

// Get fee
$fee = $this->getPayexPaymentFee();
?>

<fieldset class="form-list">
    <?php $_code = $this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div style="float:right">
                &nbsp;
            </div>
            <div style="float:left">
                <!-- Start PayEx PartPayment block -->
                <form action="<?php echo $this->getFormAction(); ?>" method="post">
                    <?php if (empty($socal_security_number)): ?>
                        <label
                            for="social-security-number-<?php echo $_code ?>"><?php echo Mage::helper('payex')->__('Social Security Number'); ?>
                            <span class="required">*</span></label><br/>
                        <input name="social-security-number" id="social-security-number-<?php echo $_code ?>"
                               title="<?php echo Mage::helper('payex')->__('Social Security Number'); ?>" placeholder="<?php echo Mage::helper('payex')->__('Social Security Number'); ?>"
                               class="required-entry input-text" type="text"/><br/>
                    <?php else: ?>
                        <label
                            for="social-security-number-<?php echo $_code ?>"><?php echo Mage::helper('payex')->__('Social Security Number'); ?>
                            <span class="required">*</span></label><br/>
                        <input name="social-security-number" id="social-security-number-<?php echo $_code ?>"
                               title="<?php echo Mage::helper('payex')->__('Social Security Number'); ?>" placeholder="<?php echo $socal_security_number; ?>"
                               class="required-entry input-text" type="text" readonly/><br/>
                    <?php endif; ?>
                </form>
                <!-- End PayEx PartPayment block -->
            </div>
            <div style="float:right"></div>
        </li>
    </ul>
</fieldset>
