<div id="payex-settings-hint">
    <p><?php echo Mage::helper('payexautopay')->__('Thank you for using the official PayEx module!'); ?></p>
    <h4><?php echo Mage::helper('payexautopay')->__('To follow the <a href="%s" target="_blank">EULA</a> you need to <a href="%s" target="_blank">register</a> the use of the module', 'http://shop.aait.se/license.txt', 'http://shop.aait.se/registration'); ?></h4>
    <br />
    <p><?php echo Mage::helper('payexautopay')->__('You use this extensions:'); ?></p>
    <ul class="modules">
        <?php foreach ($modules as $module => $version) : ?>
            <li>
                <?php echo $module . ' ' . $version['current_version']; ?>
            <?php if (version_compare($version['current_version'], $version['last_version'], '<')): ?>
                <span class="last-version"> (<?php echo Mage::helper('payexautopay')->__('Available: %s', $version['last_version']); ?>)</span>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
