<?php
/**
 * @var $this PayEx_Payments_Block_Checkout_Fee
 */
?>
<!-- Start PayEx Payment Fee -->
<?php if ($this->getPayExFeeIncludeTax() > 0): ?>
    <?php if ($this->displayCartPayExFeeBoth()): ?>
        <tr>
            <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
                <?php echo $this->getTotal()->getTitle() . ' ' . $this->getExcludeTaxLabel() ?>
            </td>
            <td style="<?php echo $this->getStyle() ?>" class="a-right">
                <?php echo $this->helper('checkout')->formatPrice($this->getPayExFeeExcludeTax()) ?>
            </td>
        </tr>
        <tr>
            <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
                <?php echo  $this->getTotal()->getTitle() . ' ' .  $this->getIncludeTaxLabel() ?>
            </td>
            <td style="<?php echo $this->getStyle() ?>" class="a-right">
                <?php echo $this->helper('checkout')->formatPrice($this->getPayExFeeIncludeTax()) ?>
            </td>
        </tr>
    <?php elseif($this->displayCartPayExFeeInclTax()): ?>
        <tr>
            <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
                <?php echo $this->getTotal()->getTitle() ?>
            </td>
            <td style="<?php echo $this->getStyle() ?>" class="a-right">
                <?php echo $this->helper('checkout')->formatPrice($this->getPayExFeeIncludeTax()) ?>
            </td>
        </tr>
    <?php else: ?>
        <tr>
            <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
                <?php echo $this->getTotal()->getTitle() ?>
            </td>
            <td style="<?php echo $this->getStyle() ?>" class="a-right">
                <?php echo $this->helper('checkout')->formatPrice($this->getPayExFeeExcludeTax()) ?>
            </td>
        </tr>
    <?php endif; ?>
<?php endif; ?>
<!-- End PayEx Payment Fee -->
