<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div style="float:left">
                <img src="<?php echo Mage::getDesign()->getSkinUrl('images/payex/masterpass-140.png'); ?>" alt="Buy with MasterPass" /><br />
            </div>
            <div style="float:left">
                <?php echo Mage::helper('payex_mp')->__('Buy with MasterPass'); ?>
            </div>
        </li>
    </ul>
</fieldset>