<?php /* @var $this PayEx_Payments_Block_Form_Billing_Agreement */ ?>
<?php $_code = $this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <label for="<?php echo $_code ?>_ba_agreement_id" class="required"><em>*</em><?php echo $this->__('Credit Card') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_ba_agreement_id" name="payment[<?php echo $this->getTransportName(); ?>]" class="required-entry">
                <option value=""><?php echo $this->__('-- Please Select Credit Card--') ?></option>
            <?php foreach ($this->getBillingAgreements() as $id => $agreementLabel): ?>
                <option value="<?php echo $id ?>"><?php echo $this->escapeHtml($agreementLabel) ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
</ul>
