<?php
/** @var $this PayEx_Payments_Block_Form_Bankdebit */
?>

<fieldset class="form-list">
    <?php $_code = $this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div style="float:left">
                &nbsp;
            </div>
            <div style="float:left">
                <!-- Start PayEx Bank Debit block -->
                <p><?php echo Mage::helper('payex')->__('Select your bank:'); ?></p>
                <?php
                    $banks = $this->getLayout()->createBlock('payex/bankdebit_banks');
                    $banks->setBlockId('bank_select');
                    echo $banks->toHtml();
                ?>
                <!-- End PayEx Bank Debit block -->
            </div>
            <div style="float:right"></div>
        </li>
    </ul>
</fieldset>

